ENROLLMENT NO: 240840116054

PRACTICAL 2

AIM: Perform data inspection, cleaning, handling missing values, duplicate removal, and data transformation using Pandas

Step 1: Create DataFrame

In [36]:
# Import pandas library and create a student dataset.
# The dataset contains ID, Name, Age, City, and Marks.
import pandas as pd

data = {
    "ID": [101,102,103,104,104,105,106,107],
    "Name": ["Rahul","Priya","Amit",None,"Riya","Ajay","Naresh","jenil"],
    "Age": [20,21,None,20,20,22,23,28],
    "city": ["Surat","Navsari","Surat","Bharuch","Bharuch","Navsari","Surat","Ahemdabad"],
    "Marks": [85,None,78,88,88,81,90,93]
}

df = pd.DataFrame(data)
df

    ID    Name   Age       city  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   jenil  28.0  Ahemdabad   93.0

Step 2: Inspect the dataset

In [37]:
# Display the first 5 rows of the dataset.
df.head()

    ID   Name   Age     city  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [38]:
# Display the last 5 rows and columns.
df.tail()

    ID    Name   Age       city  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   jenil  28.0  Ahemdabad   93.0

In [39]:
# Display detailed information about the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   city    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [40]:

# Display statistical information of numerical columns.
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [41]:
# Display the dimension of the dataset.
# Output: (number of rows, number of columns)
df.shape

(8, 5)

In [42]:
# Display the data type of each column.
df.dtypes

ID         int64
Name      object
Age      float64
city      object
Marks    float64
dtype: object

In [43]:
# Display all columns of the DataFrame.
df.columns

Index(['ID', 'Name', 'Age', 'city', 'Marks'], dtype='object')

 3: Check missing values

In [44]:
# Check for missing values in the dataset.
df.isnull()

      ID   Name    Age   city  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

In [45]:
# Count missing values in each column.
df.isnull().sum()

ID       0
Name     1
Age      1
city     0
Marks    1
dtype: int64

In [46]:
# Count total missing values in the whole dataset.
df.isnull().sum().sum()

np.int64(3)

 4: Fill missing values

In [47]:
# Replace the missing value in the Marks column with the mean.
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [48]:
# Replace the missing value in the Age column with the mean.
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [49]:
# Replace the missing value in the Name column with "unknown".
df["Name"] = df["Name"].fillna("unknown")

In [50]:
# Display the updated DataFrame.
df

    ID     Name   Age       city      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    jenil  28.0  Ahemdabad  93.000000

5: Detect duplicate records

In [51]:
# Check whether each row is duplicated.
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [52]:
# Count the total number of duplicate rows.
df.duplicated().sum()

np.int64(0)

6: Remove duplicate records

In [53]:
# Remove duplicate rows from the DataFrame.
df.drop_duplicates(inplace=True)

# Display the updated DataFrame.
df

    ID     Name   Age       city      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    jenil  28.0  Ahemdabad  93.000000

7: Rename columns

In [54]:
# Rename the Marks column to Score.
df.rename(columns={"Marks":"Score"}, inplace=True)

# Display the updated DataFrame.
df

    ID     Name   Age       city      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    jenil  28.0  Ahemdabad  93.000000

 8: Change data type

In [55]:
# Convert the Age column into integer data type.
df["Age"] = df["Age"].astype(int)

# Display the updated DataFrame.
df

    ID     Name  Age       city      Score
0  101    Rahul   20      Surat  85.000000
1  102    Priya   21    Navsari  86.142857
2  103     Amit   22      Surat  78.000000
3  104  unknown   20    Bharuch  88.000000
4  104     Riya   20    Bharuch  88.000000
5  105     Ajay   22    Navsari  81.000000
6  106   Naresh   23      Surat  90.000000
7  107    jenil   28  Ahemdabad  93.000000

9: Calculate final score

In [56]:
# Add 5 marks to the Score column and create a new column.
df["finnal score"] = df["Score"] + 5

# Display the updated DataFrame.
df

    ID     Name  Age       city      Score  finnal score
0  101    Rahul   20      Surat  85.000000     90.000000
1  102    Priya   21    Navsari  86.142857     91.142857
2  103     Amit   22      Surat  78.000000     83.000000
3  104  unknown   20    Bharuch  88.000000     93.000000
4  104     Riya   20    Bharuch  88.000000     93.000000
5  105     Ajay   22    Navsari  81.000000     86.000000
6  106   Naresh   23      Surat  90.000000     95.000000
7  107    jenil   28  Ahemdabad  93.000000     98.000000

 10: Convert names into uppercase

In [57]:
# Convert all names into uppercase letters.
df["Name"] = df["Name"].str.upper()

# Display the updated DataFrame.
df

    ID     Name  Age       city      Score  finnal score
0  101    RAHUL   20      Surat  85.000000     90.000000
1  102    PRIYA   21    Navsari  86.142857     91.142857
2  103     AMIT   22      Surat  78.000000     83.000000
3  104  UNKNOWN   20    Bharuch  88.000000     93.000000
4  104     RIYA   20    Bharuch  88.000000     93.000000
5  105     AJAY   22    Navsari  81.000000     86.000000
6  106   NARESH   23      Surat  90.000000     95.000000
7  107    JENIL   28  Ahemdabad  93.000000     98.000000

 11: Convert city names into lowercase

In [58]:
# Convert all city names into lowercase letters.
df["city"] = df["city"].str.lower()

# Display the updated DataFrame.
df

    ID     Name  Age       city      Score  finnal score
0  101    RAHUL   20      surat  85.000000     90.000000
1  102    PRIYA   21    navsari  86.142857     91.142857
2  103     AMIT   22      surat  78.000000     83.000000
3  104  UNKNOWN   20    bharuch  88.000000     93.000000
4  104     RIYA   20    bharuch  88.000000     93.000000
5  105     AJAY   22    navsari  81.000000     86.000000
6  106   NARESH   23      surat  90.000000     95.000000
7  107    JENIL   28  ahemdabad  93.000000     98.000000

12: Remove extra spaces

In [59]:
# Remove unwanted spaces from city names.
df["city"] = df["city"].str.strip()

# Display the updated DataFrame.
df

    ID     Name  Age       city      Score  finnal score
0  101    RAHUL   20      surat  85.000000     90.000000
1  102    PRIYA   21    navsari  86.142857     91.142857
2  103     AMIT   22      surat  78.000000     83.000000
3  104  UNKNOWN   20    bharuch  88.000000     93.000000
4  104     RIYA   20    bharuch  88.000000     93.000000
5  105     AJAY   22    navsari  81.000000     86.000000
6  106   NARESH   23      surat  90.000000     95.000000
7  107    JENIL   28  ahemdabad  93.000000     98.000000

13: Sort dataset

In [60]:
# Sort the dataset according to final score.
# ascending=False sorts the data from highest to lowest.
df = df.sort_values("finnal score", ascending=False)

# Display the sorted DataFrame.
df

    ID     Name  Age       city      Score  finnal score
7  107    JENIL   28  ahemdabad  93.000000     98.000000
6  106   NARESH   23      surat  90.000000     95.000000
3  104  UNKNOWN   20    bharuch  88.000000     93.000000
4  104     RIYA   20    bharuch  88.000000     93.000000
1  102    PRIYA   21    navsari  86.142857     91.142857
0  101    RAHUL   20      surat  85.000000     90.000000
5  105     AJAY   22    navsari  81.000000     86.000000
2  103     AMIT   22      surat  78.000000     83.000000

14: Save clean dataset

In [61]:
# Save the cleaned DataFrame as a CSV file.
# index=False prevents row numbers from being saved.
df.to_csv("cleaned_students.csv", index=False)

print("Dataset Saved Successfully.")

Dataset Saved Successfully.

15: Display final dataset

In [62]:
# Display the final cleaned and transformed dataset.
df

    ID     Name  Age       city      Score  finnal score
7  107    JENIL   28  ahemdabad  93.000000     98.000000
6  106   NARESH   23      surat  90.000000     95.000000
3  104  UNKNOWN   20    bharuch  88.000000     93.000000
4  104     RIYA   20    bharuch  88.000000     93.000000
1  102    PRIYA   21    navsari  86.142857     91.142857
0  101    RAHUL   20      surat  85.000000     90.000000
5  105     AJAY   22    navsari  81.000000     86.000000
2  103     AMIT   22      surat  78.000000     83.000000