ENROLLMENT NO: 240840116054

PRACTICAL 1

AIM: Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON Files using Pandas.

 Step 1: Import pandas library

In [ ]:
# Pandas is used to create, read, modify, and analyze data in table format.
import pandas as pd


 Step 2: Create student data

In [ ]:
# Here we create a dictionary containing student ID, name, age, city, and marks.
data = {
    "ID": [101,102,103,104,105,106,107],
    "Name":["Rahul","Priya","Amit","Riya","Karan","krisha","harry"],
    "Age":[20,21,19,20,22,24,28],
    "City":["surat","navsari","valsad","bharuch","surat","gandhinagar","ahemdabad"],
    "Marks":[85,92,78,88,81,84,90]
}

Step 3: Create a DataFrame

In [ ]:
# pd.DataFrame() converts the dictionary into a table with rows and columns.
df = pd.DataFrame(data)
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        surat     85
1  102   Priya   21      navsari     92
2  103    Amit   19       valsad     78
3  104    Riya   20      bharuch     88
4  105   Karan   22        surat     81
5  106  krisha   24  gandhinagar     84
6  107   harry   28    ahemdabad     90

Step 4: Save the DataFrame as a CSV file

In [ ]:
# to_csv() saves the data in CSV format.
# index=False prevents pandas from saving row numbers in the file.
df.to_csv("students.csv", index=False)
print("CSV file created successfully.")

CSV file created successfully.

Step 5: Save the DataFrame as an Excel file

In [ ]:
# to_excel() saves the data in Microsoft Excel format.
# index=False prevents row numbers from being saved.
df.to_excel("students.xlsx", index=False)
print("Excel file created successfully.")

Excel file created successfully.

Step 6: Save the DataFrame as a JSON file

In [ ]:
# to_json() saves the data in JSON format.
# orient="records" stores each row as a separate JSON record.
df.to_json("students.json", orient="records")
print("JSON file created successfully.")

JSON file created successfully.

Step 7: Read the CSV file

In [ ]:
# read_csv() loads the saved CSV file into a new DataFrame.
df_csv = pd.read_csv("students.csv")
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        surat     85
1  102   Priya   21      navsari     92
2  103    Amit   19       valsad     78
3  104    Riya   20      bharuch     88
4  105   Karan   22        surat     81
5  106  krisha   24  gandhinagar     84
6  107   harry   28    ahemdabad     90

Step 8: Read the Excel file

In [ ]:
# read_excel() loads the saved Excel file into a DataFrame.
df_excel = pd.read_excel("students.xlsx")
df_excel

    ID    Name  Age         City  Marks
0  101   Rahul   20        surat     85
1  102   Priya   21      navsari     92
2  103    Amit   19       valsad     78
3  104    Riya   20      bharuch     88
4  105   Karan   22        surat     81
5  106  krisha   24  gandhinagar     84
6  107   harry   28    ahemdabad     90

Step 9: Read the JSON file

In [ ]:
# read_json() loads the saved JSON file into a DataFrame.
df_json = pd.read_json("students.json")
df_json

    ID    Name  Age         City  Marks
0  101   Rahul   20        surat     85
1  102   Priya   21      navsari     92
2  103    Amit   19       valsad     78
3  104    Riya   20      bharuch     88
4  105   Karan   22        surat     81
5  106  krisha   24  gandhinagar     84
6  107   harry   28    ahemdabad     90

Step 10: Display the first 5 rows

In [ ]:
# head() displays the first five rows of the DataFrame.
# It is useful for quickly checking the beginning of the dataset.
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    surat     85
1  102  Priya   21  navsari     92
2  103   Amit   19   valsad     78
3  104   Riya   20  bharuch     88
4  105  Karan   22    surat     81

Step 11: Display the last 5 rows

In [ ]:
# tail() displays the last five rows of the DataFrame.
# It is useful for checking the end of the dataset.
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       valsad     78
3  104    Riya   20      bharuch     88
4  105   Karan   22        surat     81
5  106  krisha   24  gandhinagar     84
6  107   harry   28    ahemdabad     90

Step 12: Display information about the dataset

In [ ]:
# info() shows the number of rows, columns, column names,
# data types, and non-null values in the DataFrame.
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

Step 13: Display descriptive statistics

In [ ]:
# describe() gives statistical information about numerical columns.
# It shows count, mean, standard deviation, minimum, maximum, etc.
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

 Step 14: Display the shape of the dataset

In [ ]:
# shape returns the number of rows and columns.
# The result is displayed as (rows, columns).
df_csv.shape

(7, 5)

Step 15: Display all column names

In [ ]:
# columns shows the names of all columns present in the DataFrame.
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step 16: Display data types

In [ ]:
# dtypes shows the data type of each column,
# such as integer, float, or object/string.
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

Step 17: Check for missing values

In [ ]:
# isnull() identifies empty or missing values.
# sum() counts the total missing values in each column.
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

Step 18: Display a single column

In [ ]:
# Here we select only the Marks column from the DataFrame.
df_csv["Marks"]

0    85
1    92
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

 Step 19: Display multiple columns

In [ ]:
# Here we select only the Name and Marks columns.
# Multiple column names are written inside a list.
df_csv[["Name", "Marks"]]

     Name  Marks
0   Rahul     85
1   Priya     92
2    Amit     78
3    Riya     88
4   Karan     81
5  krisha     84
6   harry     90

Step 20: Filter records based on marks

In [ ]:
# This displays only students whose marks are greater than 80.
# The condition inside [] is used to filter the rows.
df_csv[df_csv["Marks"] > 80]

    ID    Name  Age         City  Marks
0  101   Rahul   20        surat     85
1  102   Priya   21      navsari     92
3  104    Riya   20      bharuch     88
4  105   Karan   22        surat     81
5  106  krisha   24  gandhinagar     84
6  107   harry   28    ahemdabad     90

Step 21: Calculate average marks

In [ ]:
# mean() calculates the average value of the Marks column.
df_csv["Marks"].mean()

np.float64(85.42857142857143)

Step 22: Sort the dataset by marks

In [ ]:
# sort_values() arranges the rows according to the Marks column.
# ascending=False sorts the marks from highest to lowest.
df_csv.sort_values(by="Marks", ascending=False)

    ID    Name  Age         City  Marks
1  102   Priya   21      navsari     92
6  107   harry   28    ahemdabad     90
3  104    Riya   20      bharuch     88
0  101   Rahul   20        surat     85
5  106  krisha   24  gandhinagar     84
4  105   Karan   22        surat     81
2  103    Amit   19       valsad     78

Step 23: Display the complete dataset

In [ ]:
# print() displays all rows and columns of the DataFrame.
print(df_csv)

    ID    Name  Age         City  Marks
0  101   Rahul   20        surat     85
1  102   Priya   21      navsari     92
2  103    Amit   19       valsad     78
3  104    Riya   20      bharuch     88
4  105   Karan   22        surat     81
5  106  krisha   24  gandhinagar     84
6  107   harry   28    ahemdabad     90